services:
  - type: web
    name: vaultbot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: UPLOAD_CHANNEL_ID
        sync: false
      - key: DB_CHANNEL_ID
        sync: false
      - key: WEBHOOK_HOST
        sync: false
      - key: PORT
        value: 10000